package com.example.component;

import java.awt.Color;
import javax.swing.Icon;

public class ChatLeftProfile extends javax.swing.JLayeredPane {

    public ChatLeftProfile() {
        initComponents();
        txt.setBackground(new Color(242,242,242));
    }
    
    public void setUserProfile(String user) {
        txt.setUserProfile(user);
    }
    
    public void setText(String text) {
        txt.setText(text);
        // Test data:
        txt.setTime("10:30 PM");
    }
    
    public void setImageProfile(Icon image) {
        iaimage.setImage(image);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        iaimage = new com.example.swing.ImageAvatar();
        txt = new com.example.component.ChatItem();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));

        iaimage.setBorderSize(0);
        iaimage.setImage(new javax.swing.ImageIcon(getClass().getResource("/avatar.png"))); // NOI18N
        iaimage.setMaximumSize(new java.awt.Dimension(31, 31));
        iaimage.setMinimumSize(new java.awt.Dimension(31, 31));
        iaimage.setPreferredSize(new java.awt.Dimension(31, 31));

        jLayeredPane1.setLayer(iaimage, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(iaimage, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(iaimage, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        add(jLayeredPane1);
        add(txt);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.example.swing.ImageAvatar iaimage;
    private javax.swing.JLayeredPane jLayeredPane1;
    private com.example.component.ChatItem txt;
    // End of variables declaration//GEN-END:variables
}
