package com.example.component;

import com.example.icon.Emogi;
import com.example.icon.ModelEmoji;
import com.example.main.Main;
import com.example.swing.ScrollBar;
import com.example.swing.WrapLayout;
import java.awt.Component;
import java.awt.Cursor;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.BoxLayout;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFileChooser;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.border.EmptyBorder;
import net.miginfocom.swing.MigLayout;

public class PanelMore extends javax.swing.JPanel {

    public PanelMore() {
        initComponents();
        init();
    }

    private void init() {
        setLayout(new MigLayout("fillx"));
        panelHeader = new JPanel();
        panelHeader.setLayout(new BoxLayout(panelHeader, BoxLayout.LINE_AXIS));
        panelHeader.add(getButtonFile());
        panelHeader.add(getEmojiStyle1());
        panelHeader.add(getEmojiStyle2());
        add(panelHeader, "w 100%, h 30!, wrap");
                
        panelDetail = new JPanel();
        panelDetail.setLayout(new WrapLayout(WrapLayout.LEFT));
        JScrollPane scrollPane = new JScrollPane(panelDetail);
        scrollPane.setBorder(null);
        scrollPane.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_NEVER);
        scrollPane.setVerticalScrollBar(new ScrollBar());
        // Test Color
//        panelDetail.setBackground(Color.yellow);
        add(scrollPane, "w 100%, h 100%");
    }
    
    private JButton getButtonFile() {
        OptionButton cmd = new OptionButton();
        cmd.setIcon(new ImageIcon(getClass().getResource("/icon/link.png")));
        cmd.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                JFileChooser fileChooser = new JFileChooser();
                fileChooser.showOpenDialog(Main.getFrames()[0]);
                //
            }
        });
        return cmd;
    }
    
    private JButton getEmojiStyle1() {
        // Test
        OptionButton cmd = new OptionButton();
        cmd.setIcon(Emogi.getInstance().getEmoji(1).toSize(25, 25).getIcon());
        cmd.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                clearSelected();
                cmd.setSelected(true);
                panelDetail.removeAll();
                for (ModelEmoji emoji : Emogi.getInstance().getStyle1()) {
                    JButton button  = new JButton(emoji.getIcon());
                    button.setName(emoji.getId() + "");
                    button.setBorder(new EmptyBorder(3, 3, 3, 3));
                    button.setCursor(new Cursor(Cursor.HAND_CURSOR));
                    button.setContentAreaFilled(false);
                    panelDetail.add(button);
                }
                panelDetail.repaint();
                panelDetail.revalidate();
            }
        });
        return cmd;
    }
    
     private JButton getEmojiStyle2() {
        // Test
        OptionButton cmd = new OptionButton();
        cmd.setIcon(Emogi.getInstance().getEmoji(21).toSize(25, 25).getIcon());
        cmd.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                clearSelected();
                cmd.setSelected(true);
                panelDetail.removeAll();
                for (ModelEmoji emoji : Emogi.getInstance().getStyle2()) {
                    JButton button  = new JButton(emoji.getIcon());
                    button.setName(emoji.getId() + "");
                    button.setBorder(new EmptyBorder(3, 3, 3, 3));
                    button.setCursor(new Cursor(Cursor.HAND_CURSOR));
                    button.setContentAreaFilled(false);
                    panelDetail.add(button);
                }
                panelDetail.repaint();
                panelDetail.revalidate();
            }
        });
        return cmd;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 515, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 84, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    
    private void clearSelected() {
        for (Component component : panelHeader.getComponents()) {
            if (component instanceof OptionButton) {
                ((OptionButton) component).setSelected(false);
            }
        }
    }
    
    private JPanel panelHeader;
    private JPanel panelDetail;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
