package com.example.form;

import com.example.component.ChatBody;
import com.example.component.ChatBottom;
import com.example.component.ChatTitle;
import com.example.event.EventChat;
import com.example.event.PublicEvent;
import com.example.model.ModelReceiveMessage;
import com.example.model.ModelSendMessage;
import com.example.model.ModelUserAccount;
import net.miginfocom.swing.MigLayout;
import com.example.service.Service; 
import org.json.JSONArray; 
import org.json.JSONObject; 

public class Chat extends javax.swing.JPanel {
    
    private ChatTitle chatTitle;
    private ChatBody chatBody;
    private ChatBottom chatBottom;
    
    public Chat() {
        initComponents();
        init();
    }

    private void init() {
        setLayout(new MigLayout("fillx", "0[fill]0", "0[]0[100%, bottom]0[shrink 0]0"));
        chatTitle = new ChatTitle();
        chatBody = new ChatBody();
        chatBottom = new ChatBottom();
        PublicEvent.getInstance().addEventChat(new EventChat() {
            @Override
            public void sendMessage(ModelSendMessage data) {
                chatBody.addItemRight(data);
            }

            @Override
            public void receiveMessage(ModelReceiveMessage data) {
                
                // ✅ FIX LOGIC: Kiểm tra NULL và ID
                if (chatTitle.getUser() != null) {
                    
                    int currentChatUserID = chatTitle.getUser().getUserID(); 
                    int myID = Service.getInstance().getUser().getUserID(); 
                    
                    // Trường hợp 1: Tin nhắn đến từ người đang chat (incoming)
                    if (data.getFromUserID() == currentChatUserID) {
                        chatBody.addItemLeft(data);
                        
                    // Trường hợp 2: Tin nhắn TÔI tự gửi cho mình từ thiết bị khác (đồng bộ)
                    } else if (data.getFromUserID() == myID && data.getToUserID() == currentChatUserID) {
                        ModelSendMessage sentMsg = new ModelSendMessage(myID, data.getToUserID(), data.getText());
                        chatBody.addItemRight(sentMsg);
                    }
                }
            }
            
            @Override
            public void loadHistory(Object historyData) {
                // Xóa chat cũ trước khi tải lịch sử
                chatBody.clearChat(); 
                
                JSONArray jsonArray = (JSONArray) historyData;
                
                for (int i = 0; i < jsonArray.length(); i++) {
                    try {
                        JSONObject json = jsonArray.getJSONObject(i);
                        // Dữ liệu từ Server là ChatMessage, nhưng ta có thể dùng ModelReceiveMessage để parse
                        ModelReceiveMessage message = new ModelReceiveMessage(json); 
                        
                        // Lấy ID của người dùng hiện tại đang đăng nhập
                        int myID = Service.getInstance().getUser().getUserID();
                        
                        if (message.getFromUserID() == myID) {
                            // Đây là tin nhắn *tôi đã gửi* (trong lịch sử)
                            // KHẮC PHỤC: Chuyển đổi sang ModelSendMessage để addItemRight chấp nhận
                            ModelSendMessage sentMsg = new ModelSendMessage(myID, message.getToUserID(), message.getText());
                            chatBody.addItemRight(sentMsg); 
                        } else {
                            // Đây là tin nhắn *tôi đã nhận* (trong lịch sử)
                            chatBody.addItemLeft(message); 
                        }
                    } catch (Exception e) {
                        System.err.println("Error processing history message: " + e.getMessage());
                    }
                }
            }
        });

        add(chatTitle, "wrap");
        add(chatBody, "wrap");
        add(chatBottom, "h ::50%");
    }
    
    public void setUser(ModelUserAccount user) {
        chatTitle.setUserName(user);
        chatBottom.setUser(user);
        chatBody.clearChat();

        Service.getInstance().requestHistory(user.getUserID());
    }
    
    public void updateUser(ModelUserAccount user) {
        chatTitle.updateUser(user);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 727, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 470, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
